### ISSUE TITLE
Connection refused(连接数据库被拒)

### ISSUE THREAD

**Issue by mercy5871** [Decalogue/chat#1]
前辈你好，我在robot = Robot()实例的过程中 报错："SocketError: Connection refused"，我猜应该是需要获取数据，不知大神有没有可以推荐的数据库或知识图谱库，能否在readme中说明一下如何设置，谢谢～

**Comment by Decalogue** [comment]
下午好！
首先我也是新手。数据库建立主要有以下几个步骤：
1.将chat/user.txt内容导入neo4j数据库（直接复制到neo4j浏览器客户端查询栏里面，运行），数据库名字您自己起，密码可初始化为"train”;
2.执行chat/tests/test_upload.py将知识库excel导入。这个可以给您分享一个xls文件，里面的结构是预先定义好的。
3.在windows上用neo4j客户端（exe安装版或者压缩包服务版都可以）启动数据库，运行chat/tests/test_server.py即可启动语义服务。
4.通过运行chat/tests/test_client.py进行对话。
谢谢！

**Comment by shishaozheng** [comment]
@Decalogue 你好，请问知识库Excel是要按照tests/testcase.xls的格式来定义吗？注意到这个excel问题一栏里多种相似文法直接连在了一起，这样怎么区分呢？或者说这么做的理由是什么呢？

**Comment by shishaozheng** [comment]
请问一下能分享一份知识库excel模板么，我在代码里只找到一个new.xls，而且格式有点问题
