### ISSUE TITLE
代码可以运行了，但场景不会用，没有详细说明介绍

### ISSUE THREAD

**Issue by zhengxijiang** [Decalogue/chat#10]
您好，chat.xls知识库里的一些参数还不会用，比如：topic、tid、ftid、behavior、parameter、url、tag、	keywords、txt、img、button、description、hot。我想使用下场景，设置self.is_scene = True，运行后报错。您能不能提供个详细的说明文档，或者详细的chat.xls，谢谢!

**Comment by zhengxijiang** [comment]
File "C:\Users\zxj\PycharmProjects\chat-master\chat\qa.py", line 562, in <listcomp>
    if item['n']['ftid'] == self.amemory[-1]['tid'] or item['n']['ftid'] == self.amemory[-1]['ftid']]
IndexError: deque index out of range
----------------------------------------

**Comment by Decalogue** [comment]
您好！场景是不用设置 self.is_scene = True 的，按照示例填写场景，只要问到了进入场景的根节点的触发问句，就自然会进入场景，self.is_scene = True 是自动的。

**Comment by Decalogue** [comment]
关于场景的示例和文档近期会更新。

**Comment by Decalogue** [comment]
早上好！请问除了场景，您的问答是可以正常运行的对吧？

**Comment by Decalogue** [comment]
早上好！

1.关于“tag”、"keywords"、"txt"、"img"、"hot"这几个参数
tag：自定义问题的核心关键词对应的语义标签，用来在匹配时大幅缩小匹配范围。
keywords：用来存储自定义问题的关键词列表，目前还没有使用到
txt：如果您有交互界面例如平板，这就是在语音回答的同时在平板上显示的内容，可以和答案 content 一样，也可以配合 content 显示更多内容
img：与 txt 类似，是在交互界面上在语音回答同时显示的自定义图片。
hot：用来统计该问题被用户问到的次数，从而根据 hot 确定用户比较关心的问题，提升用户体验。

2.请按屏幕提示操作 
这是在场景里但没有正确匹配到场景内容的情况，提示用户根据相应信息操作或者问答

3.把 robot 的实例化放到了具体的 handle 方法
您的这个建议非常好！
之前没有加场景只有问答的时候，只实例一个 robot，不同用户根据自己的 userid 来获取自定义的知识库问答的，后来因为主要做本地场景，就暂时没有把场景并发这块优化。
根据您的建议：把 robot 的实例化放到了具体的 handle 方法，因为每个用户的机器人身份不一样，所以我计划接下来在每个用户单独实例化的时候，根据其 userid 和 password 加载对应的身份和知识库。

谢谢！

**Comment by Decalogue** [comment]
@zhengxijiang 就是把确定用户身份的环节从 chat.qa.search 里面独立出来，目前只有 userid，没有 password。考虑到不同用户对知识库是要维护和操作的，所以肯定要有 password。

**Comment by Decalogue** [comment]
@zhengxijiang 已经把您加到建议贡献者列表，谢谢支持！
