### ISSUE TITLE
一个场景下只有一条问答数据的话，输入“下一步”，报异常。

### ISSUE THREAD

**Issue by zhengxijiang** [Decalogue/chat#12]
File "C:\Users\zxj\PycharmProjects\chat-master\chat\qa.py", line 540, in search
    "," + str(int(parent['ftid'])) + "] RETURN n"
ValueError: invalid literal for int() with base 10: ''

**Comment by Decalogue** [comment]
下午好！
一个场景下只有一条问答数据属于单节点场景，单节点场景只提供进入和退出，没有下一步，多层的才有
