### ISSUE TITLE
为什么topK=1，默认值为20

### ISSUE THREAD

**Issue by zhengxijiang** [Decalogue/chat#13]
def get_tag(sentence, config):
    """Get semantic tag of sentence. 获取句子语义标签。
    """
    iquestion = sentence.format(**config)
    try:
        keywords = analyse.extract_tags(iquestion, topK=1)
        keyword = keywords[0]
    except IndexError:
        keyword = iquestion
    tags = synonym_cut(keyword, 'wf') # tuple list
    if tags:
        tag = tags[0][1]
        if not tag:
            tag = keyword
    else:
        tag = keyword
    return tag

对下面这段代码不太明白：
        keywords = analyse.extract_tags(iquestion, topK=1)
        keyword = keywords[0]

**Comment by Decalogue** [comment]
@zhengxijiang 早上好！这段代码意思是获取句子核心关键词对应的语义标签。就是每个句子只需要提取一个关键词。所以 topK=1

**Comment by zhengxijiang** [comment]
您好！其实我想问的是，这里只提取一个关键词来代表整个句子，是不准确的。因为提取出来的这个关键词不能说明该句子的含义，

例如：
用户提问：'请问企业办理税务登记证应在领取营业执照多少日内办理'

经过TF-IDF algorithm的idf_freq处理后：

{'请问': 0.757095674645, '企业': 0.422177218495, '办理': 1.314710871944, '税务': 0.857766767284, '登记证': 1.1598092559, '领取': 0.81386262692, '营业执照': 0.949395840471, '多少': 0.527570686839, '日内': 0.843261751084}

根据词频统计，办理出现了2次，所以'办理': 1.314710871944值最大。

排序：tags = sorted(freq, key=freq.__getitem__, reverse=True)
<class 'list'>: ['办理', '登记证', '营业执照', '税务', '日内', '领取', '请问', '多少', '企业']

结果：tags[:topK＝1]
办理
。

用户提问其实关心的核心是"税务登记证"相关，而非“办理”，这相差甚远。

**Comment by zhengxijiang** [comment]
关键词提取很重要，关系到从图数据库中检索结果的准确性，最终反应到机器人回答的准确性。

**Comment by Decalogue** [comment]
@zhengxijiang 您好！这只是第一步粗略确定搜索范围，然后再对这一步范围内的所有句子进行和问句的相似度匹配，得分最高的才能作为候选答案。具体的语义匹配请看 chat.semantic 和 chat.qa 模块

**Comment by Decalogue** [comment]
@zhengxijiang 句子中的所有词都是参与语义相似度计算的，不只是关键词。
例如：
喧闹的大街上人山人海 VS 热闹的街道上人来人往
[('喧闹', 'Ef03A03='), ('大街', 'Bn11A02='), ('上', 'Je12B01='), ('人山人海', 'Ef03B01=')] VS [('热闹', 'Ef03A01='), (' 街道', 'Bn11A02='), ('上', 'Je12B01='), ('人来人往', 'Ef03A02=')]
（chat.semantic.similarity）similarity1:  0.9035369774919614
（chat.semantic.similarity2）similarity2:  0.8529289886639525

爷爷爱吃土豆 VS 祖父喜欢吃马铃薯
[('爷爷', 'Ah02B01='), ('爱', 'Jc07A01='), ('吃', 'Kb06A02='), ('土豆', 'Bh06A47=')] VS [('祖父', 'Ah02B01='), ('喜欢', 'Gb09A01='), ('吃', 'Kb06A02='), ('马铃薯', 'Bh06A47=')]
similarity1:  0.7631578947368421
similarity2:  1.0

联想电脑多少钱 VS 联想笔记本价格
[('联想', 'Gb01A03#'), ('电脑', 'Bo01A27='), ('多少钱', 'Dj02B01=')] VS [('联想', 'Gb01A03#'), ('笔记本', 'Bp18A03='), ('价格', 'Dj02B01=')]
similarity1:  0.7647058823529412
similarity2:  1.0

**Comment by Decalogue** [comment]
@zhengxijiang 
def get_tag(sentence, config):
"""Get semantic tag of sentence. 获取句子语义标签。
"""
这个功能是在导入知识库时和问答确定语义匹配的大范围时用的，在 chat.qa.search 中有：

    # 和问题语义标签一致的所有节点
    tag = get_tag(question, self.user)
    match_graph = "MATCH (n:NluCell) WHERE n.tag='" + tag + \
        "' and '" + ' '.join(self.usertopics) + "' CONTAINS n.topic RETURN n"
    usergraph_all = [item['n'] for item in self.graph.run(match_graph).data()]

这个 get_tag 是用来确定 usergraph_all 这个初始搜索范围的，之后才是在该范围中找到最符合问句语义的匹配问答对。

核心计算两个句子相似度的算法是 chat.semantic.similarity 与 chat.semantic.similarity2

补充：只用关键词效果不好，所以这个使用全句子分词，转换为语义标签向量，再计算相似度矩阵，之后再根据矩阵计算得到一个相似度得分。是这样来匹配的。
目前这个相似度计算不是深度学习算法，这个是个通用算法。深度学习的算法我也正在尝试。这个通用算法在2018阿里ATEC的NLP比赛数据集上可以得到F1=0.42，比一般的深度学习模型基线要好。而且这个调整阈值之后就可以根据自己的需求确定匹配的精准程度，就是准确率是可以调高的，代价是召回率降低。
