### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [Decalogue/chat#14]
Hi. I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free. 
Best Regard

**Comment by Decalogue** [comment]
@mirzazulfan Good morning！Wonderful！Thank you so much!
Best Regard

**Comment by Decalogue** [comment]
@mirzazulfan Good night！
It's pretty good! The second or the third one is ok. Could you please separate it into  three parts?
Thank you!
Best Regard

**Comment by mirzazulfan** [comment]
@Decalogue Which one do you prefer?
i'll send you files and pr.

**Comment by Decalogue** [comment]
@mirzazulfan You can go to README
文档贡献
mirzazulfan 具体内容：设计 chat LOGO

**Comment by mirzazulfan** [comment]
Looks good @Decalogue .. You can download all files and editables file in [GDrive](https://drive.google.com/drive/folders/1fhdhx-SINu6zz-0yFGRj4dvHAoZXmg-u)
Good Luck. Enjoy.

Best Regard
Mirza Zulfan

**Comment by Decalogue** [comment]
@mirzazulfan You are so kindhearted.
Best Regard

**Comment by mirzazulfan** [comment]
if you need a logo for your other project. Please let me know. Nice to see you. Good luck.
