### ISSUE TITLE
我是安装版的Neo4j，请问怎么使用Neo4j Desktop连接已经初始化好的nlu.db文件夹

### ISSUE THREAD

**Issue by KoapT** [Decalogue/chat#18]
win10

**Comment by Darylaj** [comment]
Get Cocaine near you in Beijing Telegram @hakeemhanks53  

Get Cocaine near you in Beijing Telegram @hakeemhanks53 or gmail @hakeemhanks53@gmail.com
High-quality ritalin various brands, affordable prices, discreet shipping, fast delivery, and excellent customer service available."
Coke, vape, Ritalin, Hash
