### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by fairychao** [Decalogue/chat#23]
creating build/temp.linux-x86_64-3.8/numpy/random
    creating build/temp.linux-x86_64-3.8/numpy/random/mtrand
    compile options: '-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.8/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include/python3.8 -Ibuild/src.linux-x86_64-3.8/numpy/core/src/private -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/private -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/private -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -c'
    gcc: numpy/random/mtrand/mtrand.c
    numpy/random/mtrand/mtrand.c: In function ‘PyInit_mtrand’:
    numpy/random/mtrand/mtrand.c:43380:3: warning: ‘tp_print’ is deprecated (declared at /usr/local/include/python3.8/cpython/object.h:260) [-Wdeprecated-declarations]
       __pyx_type_6mtrand_RandomState.tp_print = 0;
       ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionSave’:
    numpy/random/mtrand/mtrand.c:45208:19: error: ‘PyThreadState’ has no member named ‘exc_type’
         *type = tstate->exc_type;
                       ^
    numpy/random/mtrand/mtrand.c:45209:20: error: ‘PyThreadState’ has no member named ‘exc_value’
         *value = tstate->exc_value;
                        ^
    numpy/random/mtrand/mtrand.c:45210:17: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         *tb = tstate->exc_traceback;
                     ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionReset’:
    numpy/random/mtrand/mtrand.c:45217:22: error: ‘PyThreadState’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    numpy/random/mtrand/mtrand.c:45218:23: error: ‘PyThreadState’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    numpy/random/mtrand/mtrand.c:45219:20: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    numpy/random/mtrand/mtrand.c:45220:11: error: ‘PyThreadState’ has no member named ‘exc_type’
         tstate->exc_type = type;
               ^
    numpy/random/mtrand/mtrand.c:45221:11: error: ‘PyThreadState’ has no member named ‘exc_value’
         tstate->exc_value = value;
               ^
    numpy/random/mtrand/mtrand.c:45222:11: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         tstate->exc_traceback = tb;
               ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx__GetException’:
    numpy/random/mtrand/mtrand.c:45277:22: error: ‘PyThreadState’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    numpy/random/mtrand/mtrand.c:45278:23: error: ‘PyThreadState’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    numpy/random/mtrand/mtrand.c:45279:20: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    numpy/random/mtrand/mtrand.c:45280:11: error: ‘PyThreadState’ has no member named ‘exc_type’
         tstate->exc_type = local_type;
               ^
    numpy/random/mtrand/mtrand.c:45281:11: error: ‘PyThreadState’ has no member named ‘exc_value’
         tstate->exc_value = local_value;
               ^
    numpy/random/mtrand/mtrand.c:45282:11: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         tstate->exc_traceback = local_tb;
               ^
    numpy/random/mtrand/mtrand.c: In function ‘PyInit_mtrand’:
    numpy/random/mtrand/mtrand.c:43380:3: warning: ‘tp_print’ is deprecated (declared at /usr/local/include/python3.8/cpython/object.h:260) [-Wdeprecated-declarations]
       __pyx_type_6mtrand_RandomState.tp_print = 0;
       ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionSave’:
    numpy/random/mtrand/mtrand.c:45208:19: error: ‘PyThreadState’ has no member named ‘exc_type’
         *type = tstate->exc_type;
                       ^
    numpy/random/mtrand/mtrand.c:45209:20: error: ‘PyThreadState’ has no member named ‘exc_value’
         *value = tstate->exc_value;
                        ^
    numpy/random/mtrand/mtrand.c:45210:17: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         *tb = tstate->exc_traceback;
                     ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionReset’:
    numpy/random/mtrand/mtrand.c:45217:22: error: ‘PyThreadState’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    numpy/random/mtrand/mtrand.c:45218:23: error: ‘PyThreadState’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    numpy/random/mtrand/mtrand.c:45219:20: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    numpy/random/mtrand/mtrand.c:45220:11: error: ‘PyThreadState’ has no member named ‘exc_type’
         tstate->exc_type = type;
               ^
    numpy/random/mtrand/mtrand.c:45221:11: error: ‘PyThreadState’ has no member named ‘exc_value’
         tstate->exc_value = value;
               ^
    numpy/random/mtrand/mtrand.c:45222:11: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         tstate->exc_traceback = tb;
               ^
    numpy/random/mtrand/mtrand.c: In function ‘__Pyx__GetException’:
    numpy/random/mtrand/mtrand.c:45277:22: error: ‘PyThreadState’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    numpy/random/mtrand/mtrand.c:45278:23: error: ‘PyThreadState’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    numpy/random/mtrand/mtrand.c:45279:20: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    numpy/random/mtrand/mtrand.c:45280:11: error: ‘PyThreadState’ has no member named ‘exc_type’
         tstate->exc_type = local_type;
               ^
    numpy/random/mtrand/mtrand.c:45281:11: error: ‘PyThreadState’ has no member named ‘exc_value’
         tstate->exc_value = local_value;
               ^
    numpy/random/mtrand/mtrand.c:45282:11: error: ‘PyThreadState’ has no member named ‘exc_traceback’
         tstate->exc_traceback = local_tb;
               ^
    error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-3.8/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include/python3.8 -Ibuild/src.linux-x86_64-3.8/numpy/core/src/private -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/private -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/private -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.linux-x86_64-3.8/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.linux-x86_64-3.8/numpy/random/mtrand/mtrand.o.d" failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of numpy
  Moving to /root/.local/bin/f2py
   from /tmp/pip-uninstall-duz6l2gp/f2py
  Moving to /root/.local/bin/f2py3
   from /tmp/pip-uninstall-duz6l2gp/f2py3
  Moving to /root/.local/bin/f2py3.8
   from /tmp/pip-uninstall-duz6l2gp/f2py3.8
  Moving to /root/.local/lib/python3.8/site-packages/numpy-1.18.1.dist-info/
   from /root/.local/lib/python3.8/site-packages/~umpy-1.18.1.dist-info
  Moving to /root/.local/lib/python3.8/site-packages/numpy/
   from /root/.local/lib/python3.8/site-packages/~umpy
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dpjnkyql/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dpjnkyql/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nef4bfri/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/numpy Check the logs for full command output.

**Comment by Decalogue** [comment]
您好!请问您是在 Linux 上安装的吗?建议按照操作流程在 Windows 安装
