### ISSUE TITLE
Database 'nlu.db' is unavailable.

### ISSUE THREAD

**Issue by tearsroad** [Decalogue/chat#26]
数据库没法使用，是否能有详细的教程，需要neo4j使用对应的版本吗？

**Comment by Decalogue** [comment]
您好！
首先请确保正确安装 neo4j ，对于 Windows 有安装版和打包版。安装好后在请在配置文件 neo4j.conf 中设置
```
# The name of the database to mount
dbms.active_database=nlu.db
```
然后使用命令 neo4j start 或者桌面版启动，启动后打开浏览器 http://localhost:7474/browser/ 检查是否已启动，可输入密码查看
其次请确保 py2neo 版本对应。
谢谢！
