### ISSUE TITLE
difference with ChatterBot

### ISSUE THREAD

**Issue by Running-He** [Decalogue/chat#4]
弱弱的问一下跟这个的区别和优劣是什么？
https://github.com/gunthercox/ChatterBot

**Comment by Decalogue** [comment]
下午好！
您分享的这个链接是个非常不错的项目，我也正准备好好研究一下。人家那么多星肯定做的很好啦（哈哈）。
我做的这个特点是：
1.语义匹配支持：同义句，关键词，拼音模糊匹配；
2.支持上下文自定义场景；
3.支持知识库导入导出为 Excel；
4.应答速度：5000问答对知识量（场景或单句）在 40ms 左右
5.支持 前端可视化管理知识库，添加场景，机器人身份及知识库配置。
6.支持 Neo4j 图数据库和 SQL 数据库（正在添加中）

Todo：
1.后续添加知识图谱
2.应用新的 NLP 和机器学习算法对流程进行改进

谢谢！

**Comment by Decalogue** [comment]
补充一下，我的这个区别于纯训练语料的聊天机器人，但也会加入训练的部分。主要是可以高效回答自定义的场景，因此可以实现业务逻辑。

**Comment by Running-He** [comment]
不错不错， 我看这个是中文开源chatbot里相对比较完整的呢， 再问几个问题：
1. 如果超过5000问答对会有性能下降的问题吗？
2. Neo4J主要是用来存储哪部分的数据？
3. 知识图谱是怎么来做的？有考虑读取文章内容， 转化成知识图谱吗？
4. 新的NLP是什么？

**Comment by Decalogue** [comment]
早上好！
1.由于是基于语义标签来锚定匹配区域的，即每次都会将搜索空间锁定到很小的一个子图，所以问答对线性增长的时候性能下降不大。
2.主要存储问答对，场景节点，及知识库配置信息。
3.知识图谱正在学习和实践中，具体实现方式类似于小象学院的知识图谱课程中介绍的内容以及文因互联平时分享的一些设计思想。
有考虑，但是会晚一点实施。
4.新的NLP：基于标签树的同义句匹配（已实现），中文情感分析（利用RNN或者复现一些论文的算法来对爬虫爬到的大量文本数据进行训练），与上下文相关的一些语义算法。
谢谢！

**Comment by Decalogue** [comment]
@YC-wind 您好！匹配过程是从候选项（自定义的问答对）里面选出得分最高的同义问题，然后拿到对应的答案。关于如何选出得分最高的同义问题，自然是基于问句与候选问句的相似度计算。实现：1.将两个句子先分词，每个词转化为其在同义词词典中的语义标签，然后两个句子就变成了两个语义标签句向量。2.计算这两个语义标签向量的相似度。具体见 chat.semantic 模块中的 similarity 和 similarity2 两个算法，有详细的注释。3.对所有候选项计算相似度并排序，选出大于阈值且得分最高的作为匹配到的问题。然后就得到答案（自定义的答案）了。4.关于如何从所有自定义的问答中得到少数比较可能的候选项，涉及到语义标签以及场景判断，这是一个剪枝的过程。就是每次你问一个问题待计算的候选项数目是很少的，先快速定位到一个小范围，然后在这个小范围中找到得分最高的同义句。
谢谢！

**Comment by YC-wind** [comment]
@Decalogue 很高兴收到你的回复，还是有几个小问题问你下：
1，句子转为语义标签向量是怎么进行的，如：S1=“北京 今天 天气”，与s2 = "深圳 今天 天气",转为语言标签向量结果是什么，同义词词典有点看不懂啊！-_-
2，若QA有很多，如何快速匹配，提高匹配速度呢，能加个微信聊聊么

**Comment by Decalogue** [comment]
用的自定义词典，chat.semantic.similarity切出来带词性（自定义），词性就是语义标签。两个词的相似度就是词性的相似度计算时只需要词性相似度矩阵。chat.semantic.similarity2是先切词，然后对每个词找到其标签集合，两个词的相似度就是两个标签集合中循环各取一个计算找到最大的。然后得到词性相似度矩阵。
以后这两个方法的词性相似度矩阵计算方式都是一样的。

**Comment by Decalogue** [comment]
微信可以在chat主页README扫码，也可以直接加：yingluoqingli
QA有很多，存到知识库时给每个自定义问题都计算核心语义标签存储，匹配的时候先计算用户问句的核心语义标签，然后在知识库中找到所有与其核心语义标签一致的问答对作为候选项。
由于语义标签有上千类，所以即使自定义问答对上万，那么每次问答候选项也就几十个。所以速度不是线性增长。
