### ISSUE TITLE
配置文件中的相关数据哪里获取

### ISSUE THREAD

**Issue by KongWeibin** [Decalogue/chat#7]
请问，默认配置文件如下：
[sqlite]
host = 127.0.0.1
port = 3366
name = test
user = test
password = test
charset = utf8

[neo4j]
host = 127.0.0.1
port = 1337
name = chat
user = neo4j
password = train
charset = utf8

[path]
log = C:/nlu/log/log.txt
do_not_know = C:/nlu/log/do_not_know.txt
db = C:/nlu/data/db/nlu_sqlite.db
usbkb = D:/新知识库

[nav]
db = C:/docu/db/contentDB.db
tabel = goalvoice

[nluserver]
host = localhost
port = 7000

这些数据的作用是什么？
[path]那里的路径都是windows下面的路径吧，这些数据的格式是什么样的？

**Comment by Decalogue** [comment]
中午好！
其中主要是 [neo4j]（数据库）和 [nluserver]（本地服务器）配置，[path] 下的路径 log（追加记录实时对话） 和 do_not_know（追加记录实时回答不上的问题） 是日志文件，您可以改成自己的路径。db 是正在开发的 SQL 版本，还没完成。usbkb 是设置导入知识库的路径，在这个目录下的知识库在语义服务启动时被自动导入，路径可以自定义，关于导入的格式详见 chat/tests/chat.xls。
谢谢！

**Comment by Decalogue** [comment]
补充：chat.config 模块是与配置有关的
