### ISSUE TITLE
关于语义相似度的算法motivation

### ISSUE THREAD

**Issue by rtygbwwwerr** [Decalogue/chat#9]
hi, 关于语义标签相似度计算, 能说明一下其动机吗(或者出处), 比如为什么要将n转化为弧度值?
对应代码为semantic2.sim_tag(tag1, tag2)
math.cos(n * math.pi / 180) * ((n - d + 1) / n) * s3

**Comment by Decalogue** [comment]
您好！
关于两个标签的相似度计算，具体可参考
https://segmentfault.com/a/1190000010320214
3.5.4节

**Comment by rtygbwwwerr** [comment]
找到了算法的原始论文:<基于同义词词林的词语相似度计算方法>(东北师范大学, 田久乐,赵蔚)

**Comment by Decalogue** [comment]
@rtygbwwwerr 非常感谢！
